# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='apikey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
